### ISSUE TITLE
Saisie des méta-données d'un nouvel exercice à créer

### ISSUE THREAD

**Issue by erikmd** [pfitaxel/learn-ocaml-editor#2]
## User Story
- en tant qu'enseignant
- je veux pouvoir définir les méta-données d'un nouvel exercice
- avant de créer celui-ci

## Tests d'acceptation
- étant donné la vue Editor (en supposant qu'aucun exercice n'existe encore)
- un bandeau "New exercise" est affiché à la fin de la vue
- lorsqu'on clique sur ce bandeau "New exercise"
- alors un formulaire s'affiche permettant de choisir un identificateur (qui doit être un identifiant valide - minuscules, chiffres, tiret ou souligné, et unique) et plusieurs méta-données :
  - titre (unique)
  - description
  - une difficulté (n in [[0, 8]] / 2)

**Comment by leunam217** [comment]
Entrain de faire les préparatifs pour le pull request. (cette branche contient les ajouts de 1-us-1)
