### ISSUE TITLE
US10 - Créer un dossier PFITA avec des propositions de solutions pour les TP PFITA

### ISSUE THREAD

**Issue by RomainGrimal** [pfitaxel/learn-ocaml-editor#22]
User story 10
Créer un dossier PFITA à la racine du dépôt privé avec des propositions de solutions pour les TP PFITA (juste des fichiers au format "solution.ml", nommés par exemple tp1_solution.ml...).

**Comment by RomainGrimal** [comment]
J'ai rajouté quelques exercices de PFITA, mais il y en a sûrement qui sont manquants.

**Comment by erikmd** [comment]
OK merci.
