### ISSUE TITLE
US6 - Passage d'un exercice d'Editor vers Exercise

### ISSUE THREAD

**Issue by RomainGrimal** [pfitaxel/learn-ocaml-editor#9]
User story 6
En tant qu'enseignant, je veux pouvoir exécuter un exercice fraîchement créé dans l'éditeur afin de pouvoir le tester dans la même instance de learn-ocaml-editor (sans devoir le télécharger/déployer dans une autre instance).

**Comment by leunam217** [comment]
Done (migration-upstream branch)
